//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiAsgRAS.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiradServer
    {
        public HiradServer()
        {
            this.HiradServerLogs = new HashSet<HiradServerLog>();
        }
    
        public int Id { get; set; }
        public string SystemName { get; set; }
        public string Location { get; set; }
        public string UnitSize { get; set; }
        public string SerialNumber { get; set; }
        public string AssetTag { get; set; }
        public string PO_ { get; set; }
        public string Field7 { get; set; }
        public string ABCId { get; set; }
        public string CostCenter { get; set; }
        public string SupportStaff { get; set; }
        public string Model { get; set; }
        public string Platform { get; set; }
        public string BuildVersion { get; set; }
        public string Configuration { get; set; }
        public string IPAddress { get; set; }
        public string ILOIPAddress { get; set; }
        public string IPAddressOther { get; set; }
        public string ApplicationUse { get; set; }
        public string Function { get; set; }
        public string Processor { get; set; }
        public Nullable<double> TotalCores { get; set; }
        public string Storage { get; set; }
        public string HDDConfiguration { get; set; }
        public string RAM { get; set; }
        public string WINTELPatchSchedule { get; set; }
        public string TSMInstalled { get; set; }
        public string TSMConfigurationPath { get; set; }
        public string TSMBackupWindow { get; set; }
        public string TSMTicket_ { get; set; }
        public string IPRequestTicket_ { get; set; }
        public string CableRunTicket_ { get; set; }
        public string PortActivationTicket_ { get; set; }
        public string Rack_Stack_ { get; set; }
        public string BuildTicket { get; set; }
        public string MoveRFC { get; set; }
        public string TivoliMonitoringLicenseApproval_ { get; set; }
        public string InstallTivoliEnhancedProfile_ { get; set; }
        public string IBMToolsSRM_Parity { get; set; }
        public string QATicket_ { get; set; }
        public string DecommTicket_ { get; set; }
        public Nullable<System.DateTime> Rack_StackDate { get; set; }
        public string BuildDate { get; set; }
        public string PatchFolderInstall { get; set; }
        public string TSMexeInstall { get; set; }
        public string ArrayConfig { get; set; }
        public string NewServerForm { get; set; }
        public string SCALLANBKUP { get; set; }
        public string ISSDatabaseForm { get; set; }
        public string UpdatedAssetCenter { get; set; }
        public Nullable<System.DateTime> QASubmmissionDate { get; set; }
        public Nullable<System.DateTime> QAPassDate { get; set; }
        public string Comments { get; set; }
        public string VMHost { get; set; }
        public Nullable<bool> HiradNew { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastBootTime { get; set; }
        public string Domain { get; set; }
        public Nullable<bool> IsMonitor { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<System.DateTime> StatusTypeChangedOn { get; set; }
        public Nullable<int> NewServerId { get; set; }
    
        public virtual StatusType StatusType { get; set; }
        public virtual ICollection<HiradServerLog> HiradServerLogs { get; set; }
    }
}
