//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiAsgRAS.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusType
    {
        public StatusType()
        {
            this.HiradDbMonitors = new HashSet<HiradDbMonitor>();
            this.HiradServers = new HashSet<HiradServer>();
            this.HiradWebs = new HashSet<HiradWeb>();
        }
    
        public int Id { get; set; }
        public string StatusText { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<HiradDbMonitor> HiradDbMonitors { get; set; }
        public virtual ICollection<HiradServer> HiradServers { get; set; }
        public virtual ICollection<HiradWeb> HiradWebs { get; set; }
    }
}
